export const mockedWeatherData = {
  coord: { lon: 13.3267, lat: 52.5278 },
  weather: [{ id: 804, main: 'Clouds', description: 'overcast clouds', icon: '04n' }],
  base: 'stations',
  main: {
    temp: 0.11,
    feels_like: -4.46,
    temp_min: -0.59,
    temp_max: 0.79,
    pressure: 998,
    humidity: 89,
  },
  visibility: 10000,
  wind: { speed: 4.47, deg: 234, gust: 6.71 },
  clouds: { all: 96 },
  dt: 1668964246,
  sys: { type: 2, id: 2009543, country: 'DE', sunrise: 1668926225, sunset: 1668956867 },
  timezone: 3600,
  id: 2870310,
  name: 'Moabit',
  cod: 200,
};

export const mockedGeoCodeData = [
  {
    name: 'Berlin',
    local_names: {
      zu: 'Berlin',
      tg: 'Берлин',
      ca: 'Berlín',
      cy: 'Berlin',
      cv: 'Берлин',
      ab: 'Берлин',
      tt: 'Берлин',
      sc: 'Berlinu',
      mr: 'बर्लिन',
      ms: 'Berlin',
      si: 'බර්ලිනය',
      rm: 'Berlin',
      az: 'Berlin',
      it: 'Berlino',
      an: 'Berlín',
      fr: 'Berlin',
      zh: '柏林',
      et: 'Berliin',
      mt: 'Berlin',
      vi: 'Berlin',
      ja: 'ベルリン',
      sv: 'Berlin',
      uz: 'Berlin',
      co: 'Berlinu',
      yi: 'בערלין',
      hu: 'Berlin',
      ty: 'Berlin',
      cs: 'Berlín',
      hr: 'Berlin',
      af: 'Berlyn',
      mg: 'Berlin',
      lg: 'Berlin',
      lb: 'Berlin',
      ta: 'பெர்லின்',
      de: 'Berlin',
      eo: 'Berlino',
      ga: 'Beirlín',
      kw: 'Berlin',
      bo: 'པེ་ལིང་',
      os: 'Берлин',
      uk: 'Берлін',
      tl: 'Berlin',
      jv: 'Berlin',
      ko: '베를린',
      io: 'Berlin',
      su: 'Berliini',
      sq: 'Berlini',
      be: 'Берлін',
      qu: 'Berlin',
      sr: 'Берлин',
      es: 'Berlín',
      oc: 'Berlin',
      gn: 'Berlin',
      fi: 'Berliini',
      nl: 'Berlijn',
      ln: 'Berlin',
      cu: 'Берлинъ',
      mk: 'Берлин',
      ht: 'Bèlen',
      so: 'Berlin',
      hy: 'Բեռլին',
      eu: 'Berlin',
      ku: 'Berlîn',
      wo: 'Berlin',
      my: 'ဘာလင်မြို့',
      fo: 'Berlin',
      ro: 'Berlin',
      ie: 'Berlin',
      ug: 'Bérlin',
      bn: 'বার্লিন',
      kv: 'Берлин',
      lt: 'Berlynas',
      li: 'Berlien',
      id: 'Berlin',
      ar: 'برلين',
      th: 'เบอร์ลิน',
      no: 'Berlin',
      la: 'Berolinum',
      sh: 'Berlin',
      bg: 'Берлин',
      te: 'బెర్లిన్',
      kk: 'Берлин',
      sl: 'Berlin',
      mi: 'Pearīni',
      gv: 'Berleen',
      he: 'ברלין',
      hi: 'बर्लिन',
      nn: 'Berlin',
      sw: 'Berlin',
      ky: 'Берлин',
      lv: 'Berlīne',
      da: 'Berlin',
      bi: 'Berlin',
      gd: 'Berlin',
      tr: 'Berlin',
      fy: 'Berlyn',
      ka: 'ბერლინი',
      iu: 'ᐱᕐᓖᓐ',
      ml: 'ബെര്‍ലിന്',
      ps: 'برلين',
      gl: 'Berlín',
      am: 'በርሊን',
      mn: 'Берлин',
      kn: 'ಬೆರ್ಲಿನ್',
      sk: 'Berlín',
      pt: 'Berlim',
      fa: 'برلین',
      el: 'Βερολίνο',
      en: 'Berlin',
      pl: 'Berlin',
      yo: 'Berlin',
      is: 'Berlín',
      br: 'Berlin',
      ba: 'Берлин',
      ur: 'برلن',
      bs: 'Berlin',
      ru: 'Берлин',
      na: 'Berlin',
      se: 'Berlin',
      ia: 'Berlin',
    },
    lat: 52.5170365,
    lon: 13.3888599,
    country: 'DE',
  },
  { name: 'Berlin', lat: 44.4688795, lon: -71.1836547, country: 'US', state: 'New Hampshire' },
  { name: 'Berlin', lat: 39.7589387, lon: -89.9031635, country: 'US', state: 'Illinois' },
  { name: 'Berlin', lat: 41.621488, lon: -72.7456519, country: 'US', state: 'Connecticut' },
  { name: 'Berlin', lat: 38.3226154, lon: -75.2176892, country: 'US', state: 'Maryland' },
];
